/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `kotlin-dsl`
    java
    kotlin("jvm")
    application
    id("com.github.johnrengelman.shadow").version("8.1.1")
}

repositories { mavenCentral() }

dependencies {
    implementation(project(":common"))

    implementation("org.eclipse.jetty:jetty-server:11.0.14")
    implementation("org.eclipse.jetty:jetty-servlet:11.0.14")
    implementation("org.eclipse.jetty:jetty-servlets:11.0.14")
    implementation("org.eclipse.jetty:apache-jsp:11.0.14")

    implementation(kotlin("stdlib"))

    testImplementation(kotlin("test"))
}

application {
    // Define the main class for the application.
    mainClass.set("filesyncer.client.MainKt")
}

tasks.shadowJar { manifest { attributes["Main-Class"] = "filesyncer.client.MainKt" } }

tasks { build { dependsOn(shadowJar) } }
