/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `kotlin-dsl`
    application
}

repositories { mavenCentral() }

dependencies {
    implementation(project(":common"))

    implementation("org.eclipse.jetty:jetty-server:11.0.14")
    implementation("org.eclipse.jetty:jetty-servlet:11.0.14")
    implementation("org.eclipse.jetty:jetty-servlets:11.0.14")
    implementation("org.eclipse.jetty:apache-jsp:11.0.14")

    testImplementation(kotlin("test"))
}

application {
    // Define the main class for the application.
    mainClass.set("filesyncer.client.MainKt")
}
