/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    `kotlin-dsl`
    application
    id("com.github.johnrengelman.shadow").version("8.1.1")
    kotlin("jvm")
}

repositories { mavenCentral() }

dependencies {
    api(project(":common"))

    implementation(kotlin("stdlib"))

    testImplementation(kotlin("test"))
}

application {
    // Define the main class for the application.
    mainClass.set("filesyncer.server.MainKt")
}

tasks.shadowJar { manifest { attributes["Main-Class"] = "filesyncer.server.MainKt" } }

tasks { build { dependsOn(shadowJar) } }
