/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    `kotlin-dsl`
    application
}

repositories { mavenCentral() }

dependencies {
    api(project(":common"))

    testImplementation(kotlin("test"))
}

application {
    // Define the main class for the application.
    mainClass.set("filesyncer.server.MainKt")
}
